[[headers]]
  for = "/fixed-sitemap-1.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/fixed-sitemap-2.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"