[[redirects]]
  from = "/fixed-sitemap-1.xml"
  to = "/sitemap1.txt"
  status = 200
  force = true

[[headers]]
  for = "/sitemap1.txt"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"